FROM balenalib/%%BALENA_MACHINE_NAME%%-golang:latest-build AS build

WORKDIR /go/src/github.com/JayanSmart/smight-tasks/

COPY /app ./app
COPY go.mod ./

RUN ls -la

RUN go mod download

RUN cd app; go build

FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch

COPY --from=build /go/src/github.com/JayanSmart/smight-tasks/app .

RUN pwd

CMD ./app