/*
 * SmightTasksAPI
 *
 * A go-lang API to manage chores (repeating) and todo items (once-off)  for my household.
 *
 * API version: 0.0.1
 * Contact: jayandrinsmart@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApiResponse struct {
	Code int32 `json:"code,omitempty"`

	Type_ string `json:"type,omitempty"`

	Message string `json:"message,omitempty"`
}
