/*
 * SmightTasksAPI
 *
 * A go-lang API to manage chores (repeating) and todo items (once-off)  for my household.
 *
 * API version: 0.0.1
 * Contact: jayandrinsmart@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Task struct {
	Id int64 `json:"id,omitempty"`

	Title string `json:"title"`
	// True for tasks which are ongoing/repeating
	Repeating bool `json:"repeating"`

	Users []User `json:"users,omitempty"`
	// current status of the task
	Status string `json:"status,omitempty"`
}
