/*
 * SmightTasksAPI
 *
 * A go-lang API to manage chores (repeating) and todo items (once-off)  for my household.
 *
 * API version: 0.0.1
 * Contact: jayandrinsmart@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"AddTask",
		strings.ToUpper("Post"),
		"/tasks",
		AddTask,
	},

	Route{
		"DeleteTask",
		strings.ToUpper("Delete"),
		"/task/{taskId}",
		DeleteTask,
	},

	Route{
		"FindTasksByStatus",
		strings.ToUpper("Get"),
		"/tasks/findByStatus",
		FindTasksByStatus,
	},

	Route{
		"FindTasksByUser",
		strings.ToUpper("Get"),
		"/pet/findByUser",
		FindTasksByUser,
	},

	Route{
		"GetTaskById",
		strings.ToUpper("Get"),
		"/task/{taskId}",
		GetTaskById,
	},

	Route{
		"GetTasks",
		strings.ToUpper("Get"),
		"/tasks",
		GetTasks,
	},

	Route{
		"UpdateTask",
		strings.ToUpper("Put"),
		"/tasks",
		UpdateTask,
	},

	Route{
		"UpdateTaskWithForm",
		strings.ToUpper("Post"),
		"/task/{taskId}",
		UpdateTaskWithForm,
	},

	Route{
		"CreateUser",
		strings.ToUpper("Post"),
		"/user",
		CreateUser,
	},

	Route{
		"DeleteUser",
		strings.ToUpper("Delete"),
		"/user/{username}",
		DeleteUser,
	},

	Route{
		"GetUserByName",
		strings.ToUpper("Get"),
		"/user/{username}",
		GetUserByName,
	},

	Route{
		"UpdateUser",
		strings.ToUpper("Put"),
		"/user/{username}",
		UpdateUser,
	},
}
