/*
 * SmightTasksAPI
 *
 * A go-lang API to manage chores (repeating) and todo items (once-off)  for my household.
 *
 * API version: 0.0.1
 * Contact: jayandrinsmart@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "github.com/jayandrinsmart/smight-tasks"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
